name: box_blast_2d
description: "Box Blast 2D - Addictive Glossy 3D Marble Puzzle Game"
publish_to: 'none'

version: 1.0.2+6

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_inappwebview: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
    - assets/web/assets/
