import { ColorTheme, ObstacleType } from './types';

export type AdventureObjectiveType = 'melt_ice' | 'collect_relics' | 'target_score' | 'clear_lines';

export interface LevelInitialCell {
  r: number;
  c: number;
  obstacle: ObstacleType;
  color: ColorTheme;
}

export interface AdventureLevel {
  id: number;
  chapter: string;
  name: string;
  moves: number;
  objectiveType: AdventureObjectiveType;
  targetCount: number;
  description: string;
  initialCells?: LevelInitialCell[];
  starScores: [number, number, number]; // 1, 2, 3 stars
}

export const ADVENTURE_LEVELS: AdventureLevel[] = [
  // --- Chapter 1: Mystic Forest ---
  {
    id: 1,
    chapter: 'Mystic Forest',
    name: 'First Steps',
    moves: 14,
    objectiveType: 'clear_lines',
    targetCount: 3,
    description: 'Clear 3 lines on the board to awaken the forest portal!',
    starScores: [300, 600, 1000],
  },
  {
    id: 2,
    chapter: 'Mystic Forest',
    name: 'Ice Breaking',
    moves: 14,
    objectiveType: 'melt_ice',
    targetCount: 4,
    description: 'Melt all 4 frozen ice orbs by clearing their rows or columns!',
    initialCells: [
      { r: 2, c: 2, obstacle: 'ice', color: 'color-cyan' },
      { r: 2, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 2, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 5, obstacle: 'ice', color: 'color-cyan' },
    ],
    starScores: [400, 750, 1200],
  },
  {
    id: 3,
    chapter: 'Mystic Forest',
    name: 'Relic Hunt',
    moves: 15,
    objectiveType: 'collect_relics',
    targetCount: 6,
    description: 'Collect 6 ancient sun relics by blasting their lines!',
    initialCells: [
      { r: 1, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 1, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 6, obstacle: 'relic', color: 'color-amber' },
      { r: 6, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 6, c: 4, obstacle: 'relic', color: 'color-amber' },
    ],
    starScores: [500, 900, 1400],
  },
  {
    id: 4,
    chapter: 'Mystic Forest',
    name: 'Forest Shrine',
    moves: 13,
    objectiveType: 'target_score',
    targetCount: 800,
    description: 'Achieve 800 Points before your moves run out!',
    starScores: [800, 1200, 1800],
  },

  // --- Chapter 2: Crystal Cavern ---
  {
    id: 5,
    chapter: 'Crystal Cavern',
    name: 'Frozen Glade',
    moves: 16,
    objectiveType: 'melt_ice',
    targetCount: 8,
    description: 'Melt 8 frozen crystals encasing the cave entrance!',
    initialCells: [
      { r: 1, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 1, c: 6, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 4, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 4, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 6, obstacle: 'ice', color: 'color-sapphire' },
    ],
    starScores: [600, 1100, 1700],
  },
  {
    id: 6,
    chapter: 'Crystal Cavern',
    name: "Pharaoh's Vault",
    moves: 15,
    objectiveType: 'collect_relics',
    targetCount: 8,
    description: 'Excavate 8 royal golden relics from the inner sanctum!',
    initialCells: [
      { r: 2, c: 2, obstacle: 'relic', color: 'color-amber' },
      { r: 2, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 2, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 2, c: 5, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 2, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 5, obstacle: 'relic', color: 'color-amber' },
    ],
    starScores: [700, 1300, 1900],
  },
  {
    id: 7,
    chapter: 'Crystal Cavern',
    name: 'Combo Temple',
    moves: 15,
    objectiveType: 'clear_lines',
    targetCount: 5,
    description: 'Clear 5 full lines to resonate the cavern crystals!',
    starScores: [800, 1400, 2200],
  },
  {
    id: 8,
    chapter: 'Crystal Cavern',
    name: 'Glacier Ridge',
    moves: 16,
    objectiveType: 'melt_ice',
    targetCount: 10,
    description: 'Shatter 10 thick ice barriers across the ridge!',
    initialCells: [
      { r: 0, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 0, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 0, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 4, c: 0, obstacle: 'ice', color: 'color-cyan' },
      { r: 4, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 4, c: 4, obstacle: 'ice', color: 'color-cyan' },
    ],
    starScores: [900, 1600, 2400],
  },

  // --- Chapter 3: Cosmic Sanctuary ---
  {
    id: 9,
    chapter: 'Cosmic Sanctuary',
    name: 'Golden Treasury',
    moves: 16,
    objectiveType: 'collect_relics',
    targetCount: 10,
    description: 'Collect 10 astral relics guarding the galaxy core!',
    initialCells: [
      { r: 1, c: 2, obstacle: 'relic', color: 'color-ruby' },
      { r: 1, c: 5, obstacle: 'relic', color: 'color-ruby' },
      { r: 2, c: 1, obstacle: 'relic', color: 'color-ruby' },
      { r: 2, c: 6, obstacle: 'relic', color: 'color-ruby' },
      { r: 5, c: 1, obstacle: 'relic', color: 'color-ruby' },
      { r: 5, c: 6, obstacle: 'relic', color: 'color-ruby' },
      { r: 6, c: 2, obstacle: 'relic', color: 'color-ruby' },
      { r: 6, c: 5, obstacle: 'relic', color: 'color-ruby' },
      { r: 3, c: 3, obstacle: 'relic', color: 'color-ruby' },
      { r: 4, c: 4, obstacle: 'relic', color: 'color-ruby' },
    ],
    starScores: [1000, 1800, 2600],
  },
  {
    id: 10,
    chapter: 'Cosmic Sanctuary',
    name: 'Nebula Sweep',
    moves: 16,
    objectiveType: 'clear_lines',
    targetCount: 6,
    description: 'Clear 6 lines through the heavy cosmic nebula!',
    starScores: [1100, 1900, 2800],
  },
  {
    id: 11,
    chapter: 'Cosmic Sanctuary',
    name: 'Frost Core',
    moves: 17,
    objectiveType: 'melt_ice',
    targetCount: 12,
    description: 'Melt all 12 deep permafrost seals on the sanctuary!',
    initialCells: [
      { r: 1, c: 3, obstacle: 'ice', color: 'color-emerald' },
      { r: 1, c: 4, obstacle: 'ice', color: 'color-emerald' },
      { r: 3, c: 1, obstacle: 'ice', color: 'color-emerald' },
      { r: 3, c: 6, obstacle: 'ice', color: 'color-emerald' },
      { r: 4, c: 1, obstacle: 'ice', color: 'color-emerald' },
      { r: 4, c: 6, obstacle: 'ice', color: 'color-emerald' },
      { r: 6, c: 3, obstacle: 'ice', color: 'color-emerald' },
      { r: 6, c: 4, obstacle: 'ice', color: 'color-emerald' },
      { r: 2, c: 2, obstacle: 'ice', color: 'color-emerald' },
      { r: 2, c: 5, obstacle: 'ice', color: 'color-emerald' },
      { r: 5, c: 2, obstacle: 'ice', color: 'color-emerald' },
      { r: 5, c: 5, obstacle: 'ice', color: 'color-emerald' },
    ],
    starScores: [1200, 2100, 3000],
  },
  {
    id: 12,
    chapter: 'Cosmic Sanctuary',
    name: 'Grand Master',
    moves: 18,
    objectiveType: 'target_score',
    targetCount: 2500,
    description: 'Score 2,500 Points to complete the Ultimate Journey!',
    starScores: [2500, 3500, 5000],
  },

  // --- Chapter 4: Volcano Realm ---
  {
    id: 13,
    chapter: 'Volcano Realm',
    name: 'Lava Vent',
    moves: 16,
    objectiveType: 'clear_lines',
    targetCount: 5,
    description: 'Clear 5 full lines to vent the molten magma chambers!',
    starScores: [700, 1300, 2000],
  },
  {
    id: 14,
    chapter: 'Volcano Realm',
    name: 'Magma Melt',
    moves: 15,
    objectiveType: 'melt_ice',
    targetCount: 8,
    description: 'Melt 8 scorched permafrost stones around the caldera!',
    initialCells: [
      { r: 2, c: 4, obstacle: 'ice', color: 'color-ruby' },
      { r: 4, c: 2, obstacle: 'ice', color: 'color-ruby' },
      { r: 4, c: 6, obstacle: 'ice', color: 'color-ruby' },
      { r: 6, c: 4, obstacle: 'ice', color: 'color-ruby' },
      { r: 3, c: 3, obstacle: 'ice', color: 'color-ruby' },
      { r: 3, c: 5, obstacle: 'ice', color: 'color-ruby' },
      { r: 5, c: 3, obstacle: 'ice', color: 'color-ruby' },
      { r: 5, c: 5, obstacle: 'ice', color: 'color-ruby' },
    ],
    starScores: [800, 1500, 2400],
  },
  {
    id: 15,
    chapter: 'Volcano Realm',
    name: 'Obsidian Core',
    moves: 16,
    objectiveType: 'collect_relics',
    targetCount: 8,
    description: 'Excavate 8 glowing fire relics buried in the basalt rock!',
    initialCells: [
      { r: 1, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 1, c: 7, obstacle: 'relic', color: 'color-amber' },
      { r: 7, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 7, c: 7, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 5, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 4, obstacle: 'relic', color: 'color-amber' },
    ],
    starScores: [900, 1700, 2600],
  },
  {
    id: 16,
    chapter: 'Volcano Realm',
    name: 'Inferno Trial',
    moves: 14,
    objectiveType: 'target_score',
    targetCount: 1600,
    description: 'Score 1,600 Points before the volcanic eruption!',
    starScores: [1600, 2500, 3800],
  },

  // --- Chapter 5: Cyber Neon City ---
  {
    id: 17,
    chapter: 'Cyber Neon City',
    name: 'Neon Grid',
    moves: 16,
    objectiveType: 'clear_lines',
    targetCount: 6,
    description: 'Overcharge the city power grid by clearing 6 lines!',
    starScores: [900, 1600, 2600],
  },
  {
    id: 18,
    chapter: 'Cyber Neon City',
    name: 'Cyber Freeze',
    moves: 16,
    objectiveType: 'melt_ice',
    targetCount: 10,
    description: 'Decrypt and melt 10 encrypted ice firewall blocks!',
    initialCells: [
      { r: 2, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 2, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 6, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 6, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 1, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 4, obstacle: 'ice', color: 'color-cyan' },
      { r: 4, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 4, c: 5, obstacle: 'ice', color: 'color-cyan' },
    ],
    starScores: [1000, 1800, 2800],
  },
  {
    id: 19,
    chapter: 'Cyber Neon City',
    name: 'Data Chips',
    moves: 17,
    objectiveType: 'collect_relics',
    targetCount: 10,
    description: 'Collect 10 quantum microchips scattered across the mainframe!',
    initialCells: [
      { r: 2, c: 2, obstacle: 'relic', color: 'color-purple' },
      { r: 2, c: 6, obstacle: 'relic', color: 'color-purple' },
      { r: 6, c: 2, obstacle: 'relic', color: 'color-purple' },
      { r: 6, c: 6, obstacle: 'relic', color: 'color-purple' },
      { r: 3, c: 3, obstacle: 'relic', color: 'color-purple' },
      { r: 3, c: 5, obstacle: 'relic', color: 'color-purple' },
      { r: 5, c: 3, obstacle: 'relic', color: 'color-purple' },
      { r: 5, c: 5, obstacle: 'relic', color: 'color-purple' },
      { r: 1, c: 4, obstacle: 'relic', color: 'color-purple' },
      { r: 7, c: 4, obstacle: 'relic', color: 'color-purple' },
    ],
    starScores: [1100, 2000, 3100],
  },
  {
    id: 20,
    chapter: 'Cyber Neon City',
    name: 'Overdrive Protocol',
    moves: 15,
    objectiveType: 'target_score',
    targetCount: 2000,
    description: 'Reach 2,000 Points to breach the central firewall!',
    starScores: [2000, 3100, 4600],
  },

  // --- Chapter 6: Sunken Atlantis ---
  {
    id: 21,
    chapter: 'Sunken Atlantis',
    name: 'Coral Trench',
    moves: 15,
    objectiveType: 'clear_lines',
    targetCount: 6,
    description: 'Clear 6 lines to navigate past the deep ocean coral trench!',
    starScores: [1000, 1800, 2800],
  },
  {
    id: 22,
    chapter: 'Sunken Atlantis',
    name: 'Glacial Abyss',
    moves: 17,
    objectiveType: 'melt_ice',
    targetCount: 12,
    description: 'Melt 12 frozen seabed crystals enclosing the sunken palace!',
    initialCells: [
      { r: 1, c: 2, obstacle: 'ice', color: 'color-sapphire' },
      { r: 1, c: 6, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 7, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 7, obstacle: 'ice', color: 'color-sapphire' },
      { r: 7, c: 2, obstacle: 'ice', color: 'color-sapphire' },
      { r: 7, c: 6, obstacle: 'ice', color: 'color-sapphire' },
      { r: 3, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 3, c: 5, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 5, obstacle: 'ice', color: 'color-sapphire' },
    ],
    starScores: [1200, 2200, 3400],
  },
  {
    id: 23,
    chapter: 'Sunken Atlantis',
    name: 'Trident Jewels',
    moves: 16,
    objectiveType: 'collect_relics',
    targetCount: 10,
    description: "Recover 10 radiant gems from Poseidon's lost scepter!",
    initialCells: [
      { r: 1, c: 4, obstacle: 'relic', color: 'color-emerald' },
      { r: 2, c: 3, obstacle: 'relic', color: 'color-emerald' },
      { r: 2, c: 5, obstacle: 'relic', color: 'color-emerald' },
      { r: 3, c: 4, obstacle: 'relic', color: 'color-emerald' },
      { r: 4, c: 4, obstacle: 'relic', color: 'color-emerald' },
      { r: 5, c: 4, obstacle: 'relic', color: 'color-emerald' },
      { r: 6, c: 3, obstacle: 'relic', color: 'color-emerald' },
      { r: 6, c: 5, obstacle: 'relic', color: 'color-emerald' },
      { r: 7, c: 4, obstacle: 'relic', color: 'color-emerald' },
      { r: 8, c: 4, obstacle: 'relic', color: 'color-emerald' },
    ],
    starScores: [1200, 2200, 3500],
  },
  {
    id: 24,
    chapter: 'Sunken Atlantis',
    name: 'Sunken Temple',
    moves: 16,
    objectiveType: 'target_score',
    targetCount: 2400,
    description: 'Score 2,400 Points to unlock the ocean depths!',
    starScores: [2400, 3600, 5200],
  },

  // --- Chapter 7: Golden Olympus ---
  {
    id: 25,
    chapter: 'Golden Olympus',
    name: 'Pillar of Titans',
    moves: 17,
    objectiveType: 'clear_lines',
    targetCount: 7,
    description: 'Clear 7 celestial lines to summon the mountain staircase!',
    starScores: [1200, 2200, 3500],
  },
  {
    id: 26,
    chapter: 'Golden Olympus',
    name: 'Aegis Frost',
    moves: 17,
    objectiveType: 'melt_ice',
    targetCount: 12,
    description: 'Melt 12 sacred crystalline ice blocks guarding Mount Olympus!',
    initialCells: [
      { r: 1, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 1, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 2, c: 2, obstacle: 'ice', color: 'color-cyan' },
      { r: 2, c: 6, obstacle: 'ice', color: 'color-cyan' },
      { r: 6, c: 2, obstacle: 'ice', color: 'color-cyan' },
      { r: 6, c: 6, obstacle: 'ice', color: 'color-cyan' },
    ],
    starScores: [1400, 2500, 3800],
  },
  {
    id: 27,
    chapter: 'Golden Olympus',
    name: 'Zeus Vault',
    moves: 18,
    objectiveType: 'collect_relics',
    targetCount: 12,
    description: "Gather 12 golden lightning relics from Zeus's throne room!",
    initialCells: [
      { r: 2, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 5, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 2, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 6, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 5, obstacle: 'relic', color: 'color-amber' },
      { r: 6, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 1, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 1, c: 7, obstacle: 'relic', color: 'color-amber' },
      { r: 7, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 7, c: 7, obstacle: 'relic', color: 'color-amber' },
    ],
    starScores: [1500, 2700, 4200],
  },
  {
    id: 28,
    chapter: 'Golden Olympus',
    name: 'Crown of Gods',
    moves: 16,
    objectiveType: 'target_score',
    targetCount: 2800,
    description: 'Achieve 2,800 Points to earn the Golden Laurels!',
    starScores: [2800, 4200, 6000],
  },

  // --- Chapter 8: Void Abyss ---
  {
    id: 29,
    chapter: 'Void Abyss',
    name: 'Event Horizon',
    moves: 16,
    objectiveType: 'clear_lines',
    targetCount: 7,
    description: 'Blast 7 gravitational lines to escape the black hole pulling force!',
    starScores: [1400, 2500, 4000],
  },
  {
    id: 30,
    chapter: 'Void Abyss',
    name: 'Absolute Zero',
    moves: 18,
    objectiveType: 'melt_ice',
    targetCount: 14,
    description: 'Shatter 14 frozen void anomalies in zero-gravity space!',
    initialCells: [
      { r: 1, c: 1, obstacle: 'ice', color: 'color-purple' },
      { r: 1, c: 4, obstacle: 'ice', color: 'color-purple' },
      { r: 1, c: 7, obstacle: 'ice', color: 'color-purple' },
      { r: 3, c: 2, obstacle: 'ice', color: 'color-purple' },
      { r: 3, c: 6, obstacle: 'ice', color: 'color-purple' },
      { r: 4, c: 1, obstacle: 'ice', color: 'color-purple' },
      { r: 4, c: 4, obstacle: 'ice', color: 'color-purple' },
      { r: 4, c: 7, obstacle: 'ice', color: 'color-purple' },
      { r: 5, c: 2, obstacle: 'ice', color: 'color-purple' },
      { r: 5, c: 6, obstacle: 'ice', color: 'color-purple' },
      { r: 7, c: 1, obstacle: 'ice', color: 'color-purple' },
      { r: 7, c: 4, obstacle: 'ice', color: 'color-purple' },
      { r: 7, c: 7, obstacle: 'ice', color: 'color-purple' },
      { r: 2, c: 4, obstacle: 'ice', color: 'color-purple' },
    ],
    starScores: [1600, 2900, 4500],
  },
  {
    id: 31,
    chapter: 'Void Abyss',
    name: 'Dark Matter',
    moves: 17,
    objectiveType: 'collect_relics',
    targetCount: 12,
    description: 'Harness 12 concentrated dark matter artifacts from the abyss!',
    initialCells: [
      { r: 2, c: 3, obstacle: 'relic', color: 'color-pink' },
      { r: 2, c: 5, obstacle: 'relic', color: 'color-pink' },
      { r: 3, c: 2, obstacle: 'relic', color: 'color-pink' },
      { r: 3, c: 6, obstacle: 'relic', color: 'color-pink' },
      { r: 4, c: 1, obstacle: 'relic', color: 'color-pink' },
      { r: 4, c: 7, obstacle: 'relic', color: 'color-pink' },
      { r: 5, c: 2, obstacle: 'relic', color: 'color-pink' },
      { r: 5, c: 6, obstacle: 'relic', color: 'color-pink' },
      { r: 6, c: 3, obstacle: 'relic', color: 'color-pink' },
      { r: 6, c: 5, obstacle: 'relic', color: 'color-pink' },
      { r: 4, c: 3, obstacle: 'relic', color: 'color-pink' },
      { r: 4, c: 5, obstacle: 'relic', color: 'color-pink' },
    ],
    starScores: [1600, 3000, 4800],
  },
  {
    id: 32,
    chapter: 'Void Abyss',
    name: 'Singularity',
    moves: 16,
    objectiveType: 'target_score',
    targetCount: 3200,
    description: 'Score 3,200 Points to collapse the void core!',
    starScores: [3200, 4800, 7000],
  },

  // --- Chapter 9: Dragon's Peak ---
  {
    id: 33,
    chapter: "Dragon's Peak",
    name: 'Wyrm Cavern',
    moves: 17,
    objectiveType: 'clear_lines',
    targetCount: 8,
    description: 'Clear 8 lines through the fiery labyrinth of dragon mountain!',
    starScores: [1600, 3000, 4800],
  },
  {
    id: 34,
    chapter: "Dragon's Peak",
    name: 'Frost Dragon',
    moves: 18,
    objectiveType: 'melt_ice',
    targetCount: 14,
    description: 'Melt 14 ice crystal spikes left by the ancient Frost Wyrm!',
    initialCells: [
      { r: 0, c: 4, obstacle: 'ice', color: 'color-sapphire' },
      { r: 1, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 1, c: 5, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 2, obstacle: 'ice', color: 'color-sapphire' },
      { r: 2, c: 6, obstacle: 'ice', color: 'color-sapphire' },
      { r: 3, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 3, c: 7, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 1, obstacle: 'ice', color: 'color-sapphire' },
      { r: 5, c: 7, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 2, obstacle: 'ice', color: 'color-sapphire' },
      { r: 6, c: 6, obstacle: 'ice', color: 'color-sapphire' },
      { r: 7, c: 3, obstacle: 'ice', color: 'color-sapphire' },
      { r: 7, c: 5, obstacle: 'ice', color: 'color-sapphire' },
      { r: 8, c: 4, obstacle: 'ice', color: 'color-sapphire' },
    ],
    starScores: [1800, 3200, 5000],
  },
  {
    id: 35,
    chapter: "Dragon's Peak",
    name: 'Dragon Hoard',
    moves: 18,
    objectiveType: 'collect_relics',
    targetCount: 14,
    description: 'Claim 14 priceless ruby dragon gems from the royal hoard!',
    initialCells: [
      { r: 1, c: 2, obstacle: 'relic', color: 'color-ruby' },
      { r: 1, c: 6, obstacle: 'relic', color: 'color-ruby' },
      { r: 2, c: 3, obstacle: 'relic', color: 'color-ruby' },
      { r: 2, c: 5, obstacle: 'relic', color: 'color-ruby' },
      { r: 3, c: 4, obstacle: 'relic', color: 'color-ruby' },
      { r: 4, c: 2, obstacle: 'relic', color: 'color-ruby' },
      { r: 4, c: 4, obstacle: 'relic', color: 'color-ruby' },
      { r: 4, c: 6, obstacle: 'relic', color: 'color-ruby' },
      { r: 5, c: 4, obstacle: 'relic', color: 'color-ruby' },
      { r: 6, c: 3, obstacle: 'relic', color: 'color-ruby' },
      { r: 6, c: 5, obstacle: 'relic', color: 'color-ruby' },
      { r: 7, c: 2, obstacle: 'relic', color: 'color-ruby' },
      { r: 7, c: 6, obstacle: 'relic', color: 'color-ruby' },
      { r: 3, c: 3, obstacle: 'relic', color: 'color-ruby' },
    ],
    starScores: [1800, 3400, 5400],
  },
  {
    id: 36,
    chapter: "Dragon's Peak",
    name: 'Dragon Roar',
    moves: 16,
    objectiveType: 'target_score',
    targetCount: 3600,
    description: 'Surpass 3,600 Points to tame the mythical dragon king!',
    starScores: [3600, 5400, 8000],
  },

  // --- Chapter 10: Infinity Nexus ---
  {
    id: 37,
    chapter: 'Infinity Nexus',
    name: 'Quantum Weave',
    moves: 16,
    objectiveType: 'clear_lines',
    targetCount: 8,
    description: 'Weave 8 quantum cosmic lines to stabilize the nexus dimension!',
    starScores: [1800, 3400, 5500],
  },
  {
    id: 38,
    chapter: 'Infinity Nexus',
    name: 'Crystal Nexus',
    moves: 19,
    objectiveType: 'melt_ice',
    targetCount: 16,
    description: 'Shatter 16 multi-dimensional prism ice matrices!',
    initialCells: [
      { r: 1, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 1, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 1, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 1, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 1, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 7, c: 7, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 3, c: 5, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 3, obstacle: 'ice', color: 'color-cyan' },
      { r: 5, c: 5, obstacle: 'ice', color: 'color-cyan' },
    ],
    starScores: [2000, 3800, 6000],
  },
  {
    id: 39,
    chapter: 'Infinity Nexus',
    name: 'Infinity Relics',
    moves: 19,
    objectiveType: 'collect_relics',
    targetCount: 16,
    description: 'Gather all 16 infinity stones before time unravels!',
    initialCells: [
      { r: 0, c: 0, obstacle: 'relic', color: 'color-amber' },
      { r: 0, c: 8, obstacle: 'relic', color: 'color-amber' },
      { r: 8, c: 0, obstacle: 'relic', color: 'color-amber' },
      { r: 8, c: 8, obstacle: 'relic', color: 'color-amber' },
      { r: 2, c: 2, obstacle: 'relic', color: 'color-amber' },
      { r: 2, c: 6, obstacle: 'relic', color: 'color-amber' },
      { r: 6, c: 2, obstacle: 'relic', color: 'color-amber' },
      { r: 6, c: 6, obstacle: 'relic', color: 'color-amber' },
      { r: 1, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 1, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 7, obstacle: 'relic', color: 'color-amber' },
      { r: 7, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 3, c: 4, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 3, obstacle: 'relic', color: 'color-amber' },
      { r: 4, c: 5, obstacle: 'relic', color: 'color-amber' },
      { r: 5, c: 4, obstacle: 'relic', color: 'color-amber' },
    ],
    starScores: [2200, 4000, 6500],
  },
  {
    id: 40,
    chapter: 'Infinity Nexus',
    name: 'Omniverse Master',
    moves: 18,
    objectiveType: 'target_score',
    targetCount: 4500,
    description: 'Score a legendary 4,500 Points to conquer the Omniverse!',
    starScores: [4500, 6800, 10000],
  },
];

// Progress Management Helpers
export function getUnlockedLevel(): number {
  const val = localStorage.getItem('box_blast_adventure_unlocked');
  return val ? Math.max(1, parseInt(val, 10)) : 1;
}

export function unlockNextLevel(completedLevelId: number): void {
  const currentUnlocked = getUnlockedLevel();
  if (completedLevelId >= currentUnlocked && completedLevelId < ADVENTURE_LEVELS.length) {
    localStorage.setItem('box_blast_adventure_unlocked', String(completedLevelId + 1));
  }
}

export function getLevelStars(levelId: number): number {
  const val = localStorage.getItem(`box_blast_level_${levelId}_stars`);
  return val ? parseInt(val, 10) : 0;
}

export function saveLevelStars(levelId: number, stars: number): void {
  const existing = getLevelStars(levelId);
  if (stars > existing) {
    localStorage.setItem(`box_blast_level_${levelId}_stars`, String(stars));
  }
}

export function calculateStars(level: AdventureLevel, score: number): number {
  if (score >= level.starScores[2]) return 3;
  if (score >= level.starScores[1]) return 2;
  return 1;
}
